name: Terraform Workflow

on:
  push: {}
  
jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Verify workspace
      run: |
        ls -la
