name: Terraform Workflow

on:
  push: {}
  
jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
    - name: Init
      run: |
        terraform version
        terraform init
        terraform validate
    - name: Plan
      run: |
        terraform plan -out plan.tfplan
  Apply:
    runs-on: ubuntu-latest
    steps:
      - name: Apply
        run: |
          terraform apply plan.tfplan
    
